name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - wheel-build-libucxx
      - wheel-build-ucxx
      - wheel-build-distributed-ucxx
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.12
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  wheel-build-libucxx:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_libucxx.sh
  wheel-build-ucxx:
    needs: wheel-build-libucxx
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_ucxx.sh
  wheel-build-distributed-ucxx:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_distributed_ucxx.sh
